# Generated by Django 6.0 on 2025-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout_type', models.CharField(choices=[('walk', 'Walking'), ('run', 'Running'), ('gym', 'Gym'), ('cycle', 'Cycling'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
